version: "3"
services:

  discovery-microservice:
    build: ./discovery-microservice
    ports:
     - "8001:8001"

  configuration-microservice:
    build: ./configuration-microservice
    ports:
     - "8002:8002"
    depends_on:
     - discovery-microservice

  redis:
    build: ./redis
    ports:
      - "6379:6379"

  mongodb:
    build: ./mongodb
    ports:
     - "27017:27017"

  gateway-microservice:
    build: ./gateway-microservice
    ports:
     - "8000:8000"
    depends_on:
     - discovery-microservice
     - configuration-microservice

  cart-microservice:
    build: ./cart-microservice
    ports:
     - "9002:9002"
    depends_on:
     - discovery-microservice
     - configuration-microservice
     - gateway-microservice
     - redis

  product-catalog-microservice:
    build: ./product-catalog-microservice
    ports:
     - "9001:9001"
     - "4444:4444"
    depends_on:
     - discovery-microservice
     - configuration-microservice
     - gateway-microservice
     - mongodb
