apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: e-commerce
configMapGenerator:
  - name: cart-configmap
    literals: 
    - SPRING_REDIS_HOST=redis-service.platform-services.svc.cluster.local
    - SPRING_REDIS_PORT=6379
    - SPRING_REDIS_PASSWORD=
generatorOptions:
  disableNameSuffixHash: true # use a static name

bases:
- ../../../base/cart