name: cart App Build and Push to ECR

on:
  push:
    branches:
      - main
    paths:
      - "cart-cna-microservice/**"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: aws_configure

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cart
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd cart-cna-microservice
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Checkout GitOps repository
        uses: actions/checkout@v3
        with:
          repository: SeSAC-Team1/gitops-for-e-commerce-microservices
          token: ${{ secrets.GITOPS_TOKEN }} # 내 계정의 토큰을 사용하면 됨

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Update Kubernetes manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cart
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd cart
          kustomize edit set image $ECR_REGISTRY/$ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions' 
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update cart image tag to ${{ github.sha }}"
          git push
